---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: niri-os
# description will be included in the image's metadata
description: niri atomic fedora image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
      copr:
        - atim/starship
        - avengemedia/dms
        - avengemedia/danklinux
    group-install:
      with-optional: true
      packages:
        - printing
    install:
      packages:
        # desktop stack
        - niri
        - dms
        - sddm
        - wdisplays
        - brightnessctl
        - wlsunset
        - xwayland-satellite
        - matugen
        - dsearch
        - nemo
        - khal

        # audio stack
        - pipewire
        - wireplumber
        - pipewire-pulseaudio
        - cava

        # daemons, polkits, etc.
        - power-profiles-daemon
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - NetworkManager
        - network-manager-applet
        - bluez

        # fonts
        - google-noto-fonts-all
        - google-noto-fonts-all-vf

        # shell/terminal
        - alacritty
        - fish
        - starship
        - fastfetch
        - git

        # misc
        - code
        - distrobox
        - waydroid
        - steam-devices
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - toolbox
        - fuzzel

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.brave.Browser
          - com.github.ryonakano.pinit
          - org.gnome.Lollypop
          - org.nomacs.ImageLounge
          - io.github.celluloid_player.Celluloid
          - io.github.DenysMb.Kontainer
          - com.valvesoftware.Steam
          - io.github.kolunmi.Bazaar
          - org.kde.ark
          
      - scope: user # Also add Flathub user repo, but no user packages

  # Brew
  - type: brew
    nofile-limits: true
    brew-analytics: false
    auto-update: true
    auto-upgrade: true

  # Enable/disable system services expected for this image.
  - type: systemd
    system:
      enabled:
        - sddm.service
        - waydroid-container
        - power-profiles-daemon
    user:
      enabled:
        - dms.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
